version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.18.1
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      BEARER_TOKEN: 'no_bearer_token'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DISK_USE_READONLY_PERCENTAGE: 100
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'

  plugin_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BEARER_TOKEN: no_bearer_token
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 8081
      DATASTORE: weaviate
      WEAVIATE_HOST: http://weaviate
    ports:
      - 8081:8081
